<?php
/**
 * This file is part of the <User> project.
 *
 * @category   BootStrap_Repositories
 * @package    Repository
 * @author Etienne de Longeaux <etienne.delongeaux@gmail.com>
 * @since 2012-01-02
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace BootStrap\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use BootStrap\TranslationBundle\Repository\TranslationRepository;

/**
 * User Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * @category   BootStrap_Repositories
 * @package    Repository
 *
 * @author Etienne de Longeaux <etienne.delongeaux@gmail.com>
 */
class UserRepository extends TranslationRepository
{
	/**
	 * Gets all entities by one category.
	 *
	 * @return array\entity
	 * @access public
	 *
	 * @author Etienne de Longeaux <etienne.delongeaux@gmail.com>
	 * @since 2012-03-15
	 */
	public function getAllByParams($category = '', $MaxResults = null, $ORDER_PublishDate = '', $ORDER_Position = '', $enabled = true, $is_home_page = true)
	{
		$em = $this->createQueryBuilder('a')
			->select('a')
			->leftJoin('a.individual', 'i')
			->leftJoin('a.corporation', 'c');
	
		$em
			->andWhere('a.enabled = 1');
		
		if($is_home_page){
			$orModule = $em->expr()->orx();
			$orModule->add($em->expr()->eq('i.highlighted', 1));
			$orModule->add($em->expr()->eq('c.highlighted', 1));
			$em->andWhere($orModule);
		}

		if(!empty($ORDER_PublishDate) && !empty($ORDER_Position)){
			$em
			->orderBy('a.created_at', $ORDER_PublishDate)
			->addOrderBy('a.position', $ORDER_Position);
		}elseif(!empty($ORDER_PublishDate) && empty($ORDER_Position)){
			$em
			->orderBy('a.created_at', $ORDER_PublishDate);
		}elseif(empty($ORDER_PublishDate) && !empty($ORDER_Position)){
			$em
			->orderBy('a.position', $ORDER_Position);
		}
	
		if(!is_null($MaxResults))
			$em->setMaxResults($MaxResults);
	
		return $em;
	}	
}