imports:
    - { resource: parameters.ini }
    - { resource: "@BootStrapUserBundle/Resources/config/config.yml" }
    - { resource: "@BootStrapUserBundle/Resources/config/security.yml" }

framework:
    #esi:             ~    # esi: { enabled: true }
    # The fallback option defines the fallback locale when a translation does not exist
    # in the user's locale
    translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
        lifetime:       3600    
        
# Twig Configuration
twig:
    charset:              %kernel.charset%
    debug:                %kernel.debug%
    strict_variables:     %kernel.debug%
    auto_reload:          ~
    exception_controller:  Symfony\Bundle\TwigBundle\Controller\ExceptionController::showAction 

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Ressources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Ressources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Ressources/java/yuicompressor-2.4.7.jar
            

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
#   host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
#    port:                 587
#    encryption:           ssl
#    auth_mode:            login
#    spool:
#        type:                 file
#        path:                 "%kernel.cache_dir%/swiftmailer/spool"
#    sender_address:       ~
#    antiflood:
#        threshold:            99
#        sleep:                0
#    delivery_address:     ~
#    disable_delivery:     ~
#    logging:              "%kernel.debug%"    

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false