<?php
/**
 * This file is part of the <Admin> project.
 * 
 * @category   Admin_Repositories
 * @package    Repository
 * @author Etienne de Longeaux <etienne.delongeaux@gmail.com>
 * @since 2012-01-06
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace PiApp\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use BootStrap\TranslationBundle\Repository\TranslationRepository;

/**
 * KeyWord Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * @category   Admin_Repositories
 * @package    Repository
 * 
 * @author Etienne de Longeaux <etienne.delongeaux@gmail.com>
 */
class KeyWordRepository extends TranslationRepository
{
	/**
	 * Return all keyword.
	 *
	 * @return \PiApp\AdminBundle\Entity\Page
	 * @access public
	 *
	 * @author Etienne de Longeaux <etienne.delongeaux@gmail.com>
	 * @since 2012-01-23
	 */
	public function getAllPageKeyWords()
	{
		$query = $this->createQueryBuilder('k')
		->select('k')
		->where('k.enabled = :enabled')
		->orderBy('k.groupname', 'ASC')
		->setParameter('enabled', 1);
		//return $query->getQuery()->setMaxResults(1)->getArrayResult();
	
		return $query;
	}	
	
	/**
	 * Gets all groupname of key word.
	 *
	 * @return array
	 * @access public
	 *
	 * @author Etienne de Longeaux <etienne.delongeaux@gmail.com>
	 * @since 2012-03-28
	 */
	public function getArrayAllGroupName()
	{
		$query = $this->createQueryBuilder('k')
		->select('k.groupname')
		->where('k.enabled = :enabled')
		->setParameters(array(
				'enabled'	=> 1,
		));
		//return $query->getQuery()->setMaxResults(1)->getArrayResult();
	
		$result = array();
		$data	= $query->getQuery()->getArrayResult();
		if ($data && is_array($data) && count($data)) {
			foreach ($data as $row) {
				if(!empty($row['groupname']))
					$result[ $row['groupname'] ] = $row['groupname'];
			}
		}
		return $result;
	}
	
}