<?php
/**
 * This file is part of the <Admin> project.
 * 
 * @category   Admin_Repositories
 * @package    Repository
 * @author (c) <etienne de Longeaux> <etienne.delongeaux@gmail.com>
 * @since 2011-12-28
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace PiApp\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use BootStrap\TranslationBundle\Repository\TreeRepository;

/**
 * Rubrique Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * @category   Admin_Repositories
 * @package    Repository
 * 
 * @author (c) <etienne de Longeaux> <etienne.delongeaux@gmail.com>
 */
class RubriqueRepository extends TreeRepository
{
	/**
	 * Return all Rubrique.
	 *
	 * @return \PiApp\AdminBundle\Entity\Rubrique
	 * @access public
	 *
	 * @author (c) <etienne de Longeaux> <etienne.delongeaux@gmail.com>
	 * @since 2012-01-23
	 */
	public function getAllPageRubrique()
	{
		$query = $this->createQueryBuilder('r')
	            		->select('r')
	            		->where('r.enabled = :enabled')
	            		->orderBy('r.lft', 'ASC')
	            		->setParameter('enabled', 1);
		//return $query->getQuery()->setMaxResults(1)->getArrayResult();
	
		return $query;
	}	
}