parameters:
#    or_app_or_template.example.class: OrApp\OrTemplateBundle\Example

services:
#    or_app_or_template.example:
#        class: %or_app_or_template.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
