parameters:
    piapp.gedmo.repository.class: PiApp\GedmoBundle\Repository\Repository
    
    piapp.gedmo.event_subscriber.media.class: PiApp\GedmoBundle\EventSubscriber\EventSubscriberMedia
    piapp.gedmo.event_subscriber.position.class: PiApp\GedmoBundle\EventSubscriber\EventSubscriberPosition
    
services:
    #
    # configuration of the main repository manager allowed for the repository management
    #  
    pi_app_gedmo.repository:
        class: %piapp.gedmo.repository.class%
        arguments: ['@doctrine.orm.entity_manager']
        
    #
    # configuration of the event subscriber of entities
    #         
    pi_app_admin.event_subscriber.media:
        class: %piapp.gedmo.event_subscriber.media.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber }  
            
    pi_app_admin.event_subscriber.position:
        class: %piapp.gedmo.event_subscriber.position.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber }                        