<?php
/**
 * This file is part of the <name> project.
 *
 * @author Etienne de Longeaux <etienne.delongeaux@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace BootStrap\MediaBundle\Entity;

use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;


/**
 * 
 * @ORM\Table
 * @ORM\HasLifecycleCallbacks()
 * 
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author Etienne de Longeaux <etienne.delongeaux@gmail.com>
 */
class Media extends BaseMedia
{

    /**
     * @var integer $id
     */
    protected $id;
    
    /**
     * @var array
     */
    protected $heritage;    

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Get id
     *
     * @return integer $id
     */
    public function setId($id)
    {
    	$this->id = $id;
    }  

    /**
     *
     * This method is used when you want to convert to string an object of
     * this Entity
     * ex: $value = (string)$entity;
     *
     */
    public function __toString()
    {
    	return (string) $this->getId();
    }
    
    /**
     * Set Role
     *
     * @param array $heritage
     */
    public function setHeritage( array $heritage)
    {
    	$this->heritage = array();
    
    	foreach ($heritage as $role) {
    		$this->addRoleInHeritage($role);
    	}
    }
    
    /**
     * Get heritage
     *
     * @return array
     */
    public function getHeritage()
    {
    	return $this->heritage;
    }
    
    /**
     * Adds a role heritage.
     *
     * @param string $role
     */
    public function addRoleInHeritage($role)
    {
    	$role = strtoupper($role);
    
    	if (!in_array($role, $this->heritage, true)) {
    		$this->heritage[] = $role;
    	}
    }    
        
}