<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PiAppAdminBundleEntityTranslationPageProxy extends \PiApp\AdminBundle\Entity\TranslationPage implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function slugify($text)
    {
        $this->__load();
        return parent::slugify($text);
    }

    public function setSlug($slug)
    {
        $this->__load();
        return parent::setSlug($slug);
    }

    public function getSlug()
    {
        $this->__load();
        return parent::getSlug();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setLangStatus($langStatus)
    {
        $this->__load();
        return parent::setLangStatus($langStatus);
    }

    public function getLangStatus()
    {
        $this->__load();
        return parent::getLangStatus();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setSecure($secure)
    {
        $this->__load();
        return parent::setSecure($secure);
    }

    public function getSecure()
    {
        $this->__load();
        return parent::getSecure();
    }

    public function setHeritage(array $heritage)
    {
        $this->__load();
        return parent::setHeritage($heritage);
    }

    public function getHeritage()
    {
        $this->__load();
        return parent::getHeritage();
    }

    public function addRoleInHeritage($role)
    {
        $this->__load();
        return parent::addRoleInHeritage($role);
    }

    public function setIndexable($indexable)
    {
        $this->__load();
        return parent::setIndexable($indexable);
    }

    public function getIndexable()
    {
        $this->__load();
        return parent::getIndexable();
    }

    public function setBreadcrumb($breadcrumb)
    {
        $this->__load();
        return parent::setBreadcrumb($breadcrumb);
    }

    public function getBreadcrumb()
    {
        $this->__load();
        return parent::getBreadcrumb();
    }

    public function setMetaTitle($metaTitle)
    {
        $this->__load();
        return parent::setMetaTitle($metaTitle);
    }

    public function getMetaTitle()
    {
        $this->__load();
        return parent::getMetaTitle();
    }

    public function setMetaKeywords($metaKeywords)
    {
        $this->__load();
        return parent::setMetaKeywords($metaKeywords);
    }

    public function getMetaKeywords()
    {
        $this->__load();
        return parent::getMetaKeywords();
    }

    public function setMetaDescription($metaDescription)
    {
        $this->__load();
        return parent::setMetaDescription($metaDescription);
    }

    public function getMetaDescription()
    {
        $this->__load();
        return parent::getMetaDescription();
    }

    public function setSurtitre($surtitre)
    {
        $this->__load();
        return parent::setSurtitre($surtitre);
    }

    public function getSurtitre()
    {
        $this->__load();
        return parent::getSurtitre();
    }

    public function setTitre($titre)
    {
        $this->__load();
        return parent::setTitre($titre);
    }

    public function getTitre()
    {
        $this->__load();
        return parent::getTitre();
    }

    public function setSoustitre($soustitre)
    {
        $this->__load();
        return parent::setSoustitre($soustitre);
    }

    public function getSoustitre()
    {
        $this->__load();
        return parent::getSoustitre();
    }

    public function setDescriptif($descriptif)
    {
        $this->__load();
        return parent::setDescriptif($descriptif);
    }

    public function getDescriptif()
    {
        $this->__load();
        return parent::getDescriptif();
    }

    public function setChapo($chapo)
    {
        $this->__load();
        return parent::setChapo($chapo);
    }

    public function getChapo()
    {
        $this->__load();
        return parent::getChapo();
    }

    public function setTexte($texte)
    {
        $this->__load();
        return parent::setTexte($texte);
    }

    public function getTexte()
    {
        $this->__load();
        return parent::getTexte();
    }

    public function setPs($ps)
    {
        $this->__load();
        return parent::setPs($ps);
    }

    public function getPs()
    {
        $this->__load();
        return parent::getPs();
    }

    public function setPage(\PiApp\AdminBundle\Entity\Page $page)
    {
        $this->__load();
        return parent::setPage($page);
    }

    public function getPage()
    {
        $this->__load();
        return parent::getPage();
    }

    public function addTag(\PiApp\AdminBundle\Entity\Tag $tags)
    {
        $this->__load();
        return parent::addTag($tags);
    }

    public function setTags($tags)
    {
        $this->__load();
        return parent::setTags($tags);
    }

    public function getTags()
    {
        $this->__load();
        return parent::getTags();
    }

    public function addComment(\PiApp\AdminBundle\Entity\Comment $comments)
    {
        $this->__load();
        return parent::addComment($comments);
    }

    public function getComments()
    {
        $this->__load();
        return parent::getComments();
    }

    public function setLangCode(\PiApp\AdminBundle\Entity\Langue $langCode)
    {
        $this->__load();
        return parent::setLangCode($langCode);
    }

    public function getLangCode()
    {
        $this->__load();
        return parent::getLangCode();
    }

    public function addHistoricalStatus(\PiApp\AdminBundle\Entity\HistoricalStatus $historicalStatus)
    {
        $this->__load();
        return parent::addHistoricalStatus($historicalStatus);
    }

    public function getHistoricalStatus()
    {
        $this->__load();
        return parent::getHistoricalStatus();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }

    public function setPublishedAt($publishedAt)
    {
        $this->__load();
        return parent::setPublishedAt($publishedAt);
    }

    public function getPublishedAt()
    {
        $this->__load();
        return parent::getPublishedAt();
    }

    public function setArchiveAt($archiveAt)
    {
        $this->__load();
        return parent::setArchiveAt($archiveAt);
    }

    public function getArchiveAt()
    {
        $this->__load();
        return parent::getArchiveAt();
    }

    public function setEnabled($enabled)
    {
        $this->__load();
        return parent::setEnabled($enabled);
    }

    public function getEnabled()
    {
        $this->__load();
        return parent::getEnabled();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'page', 'tags', 'comments', 'langCode', 'langStatus', 'status', 'historicalStatus', 'secure', 'heritage', 'indexable', 'breadcrumb', 'slug', 'meta_title', 'meta_keywords', 'meta_description', 'surtitre', 'titre', 'soustitre', 'descriptif', 'chapo', 'texte', 'ps', 'created_at', 'updated_at', 'published_at', 'archive_at', 'enabled');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}